// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "UIKit App",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "UIKit App",
            targets: ["AppModule"],
            bundleIdentifier: "com.bhavinp.Ship.Destroyer",
            teamIdentifier: "6VRG2CGHH5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .arcadeGames
        )
    ],
    dependencies: [
        .package(url: "https://github.com/BhavinPat/WWDC23ResourcesSwiftPackage", branch: "main")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "WWDC23ResourcesSwiftPackage", package: "wwdc23resourcesswiftpackage")
            ],
            path: "."
        )
    ]
)
